import React, { useState } from 'react';
import {
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  Play,
  ArrowRight,
  Terminal,
  FileCode,
  Lock,
  Layers,
  Activity,
  CheckCircle2,
  XCircle,
  Cpu
} from 'lucide-react';
import { SAMPLE_DATASETS } from '../analyzerEngine';

interface AttackSimulationViewProps {
  onLoadAndAnalyze: (sampleId: string) => void;
}

interface AttackScenario {
  id: string;
  sampleId: string;
  title: string;
  category: 'Classical Cryptography' | 'Protocol & State' | 'Quantum Channel';
  severity: 'Critical' | 'High' | 'Medium';
  vector: string;
  standardsReference: string;
  mechanism: string;
  expectedIndicators: string[];
  samplePreviewSnippet: string;
}

const ATTACK_SCENARIOS: AttackScenario[] = [
  {
    id: 'forgery',
    sampleId: 'test_3_forgery_attack.txt',
    title: 'Digital Signature Forgery',
    category: 'Classical Cryptography',
    severity: 'Critical',
    vector: 'Mathematical Digest & Signature Inconsistency',
    standardsReference: 'NIST FIPS 186-5 / RFC 8017',
    mechanism:
      'Attacker constructs an invalid mathematical signature or alters signature bytes without access to the private signing key.',
    expectedIndicators: [
      'Cryptographic verification fails (digest != decrypted signature)',
      'Hash mismatch detected between calculated SHA-256 and signed hash',
      'Integrity status marked as COMPROMISED'
    ],
    samplePreviewSnippet:
      'Algorithm: RSA-2048-PKCS1v15\nSignature: 3c9b7e... (Corrupted bytes)\nStatus: INVALID_SIGNATURE'
  },
  {
    id: 'replay',
    sampleId: 'test_2_replay_attack.txt',
    title: 'Replay Attack',
    category: 'Protocol & State',
    severity: 'High',
    vector: 'Nonce Reuse & Stale Timestamp Ingestion',
    standardsReference: 'NIST SP 800-63B § 5.2.8',
    mechanism:
      'An eavesdropper captures a legitimate past signed authorization payload and transmits it again to induce duplicate credit/execution.',
    expectedIndicators: [
      'Transaction Identifier / Nonce found in previously seen ledger store',
      'Timestamp outside valid freshness delta window (> 300s)',
      'Stateful replay engine triggers REPLAY_DETECTED'
    ],
    samplePreviewSnippet:
      'Txn-ID: TXN-REPLAY-99214\nNonce: 8f4a210c (Reused in Store)\nTimestamp: 2026-09-14T08:00:00Z (Expired)'
  },
  {
    id: 'impersonation',
    sampleId: 'test_4_impersonation.txt',
    title: 'Signer Impersonation',
    category: 'Classical Cryptography',
    severity: 'High',
    vector: 'Untrusted Identity & Rogue Certificate Authority',
    standardsReference: 'ITU-T X.509 / RFC 5280',
    mechanism:
      'Payload signed by a keypair not registered in the authoritative public key directory or generated by an unauthorized identity.',
    expectedIndicators: [
      'Signer certificate subject not found in authorized entity directory',
      'Trust chain fails verification against trusted Root CA anchors',
      'Authentication marked as UNTRUSTED_SIGNER'
    ],
    samplePreviewSnippet:
      'Signer: rogue.operator@untrusted-lab.org\nIssuer: Self-Signed CA (Untrusted)\nSubject CN: Adversary Proxy'
  },
  {
    id: 'tampering',
    sampleId: 'test_5_tampering.txt',
    title: 'File Integrity & Payload Tampering',
    category: 'Classical Cryptography',
    severity: 'High',
    vector: 'In-Transit Message Modification',
    standardsReference: 'NIST FIPS 180-4 (Secure Hash Standard)',
    mechanism:
      'Message body or financial payload values altered in transit (e.g. transfer amount 100 -> 90000) while retaining the original signature.',
    expectedIndicators: [
      'SHA-256 payload digest mismatch against reference hash',
      'File integrity verification failed',
      'Cryptographic verification detects bit alteration'
    ],
    samplePreviewSnippet:
      'Amount: $90,000.00 (Modified from original $100.00)\nPayload Checksum: FAILED\nCalculated Hash != Signed Hash'
  },
  {
    id: 'quantum-eavesdrop',
    sampleId: 'test_6_quantum_eavesdropping.txt',
    title: 'Quantum Eavesdropping (Entangle-and-Measure)',
    category: 'Quantum Channel',
    severity: 'Critical',
    vector: 'Quantum State Disturbance & QBER Elevation',
    standardsReference: 'Bennett-Brassard (BB84) & QDS Protocol Bounds',
    mechanism:
      'Adversary Eve performs projective measurement on entangled quantum states during distribution, introducing quantum bit errors.',
    expectedIndicators: [
      'Simulated Quantum Bit Error Rate (QBER) exceeds the 11.0% threshold (~14.2%)',
      'Bell-state parity mismatch across distributed states',
      'Quantum channel status marked as COMPROMISED'
    ],
    samplePreviewSnippet:
      'Bell State: |Phi+>\nObserved QBER: 14.2% (Threshold: 11.0%)\nQuantum Eavesdropping Indicator: DETECTED'
  },
  {
    id: 'intercept-resend',
    sampleId: 'test_7_intercept_resend.txt',
    title: 'Quantum Intercept-Resend Attack',
    category: 'Quantum Channel',
    severity: 'Critical',
    vector: 'Basis Incompatible Resend Disturbance',
    standardsReference: 'QDS Teleportation Security Bounds',
    mechanism:
      'Eve intercepts transmitted qubits, measures in a random basis (rectilinear or diagonal), and resends reconstructed qubits.',
    expectedIndicators: [
      'Teleportation state fidelity drops toward 50%',
      'QBER spikes up to ~25.0% error rate',
      'Eavesdropping probability estimated at ~99.4%'
    ],
    samplePreviewSnippet:
      'Channel Mode: INTERCEPT_RESEND\nAverage Fidelity: 0.52\nDisturbance Pattern: Incompatible Basis Resend'
  },
  {
    id: 'expired-cert',
    sampleId: 'test_8_expired_cert.txt',
    title: 'Expired Certificate & PKI Failure',
    category: 'Classical Cryptography',
    severity: 'Medium',
    vector: 'Cryptographic Validity Period Expiration',
    standardsReference: 'RFC 5280 § 4.1.2.5',
    mechanism:
      'Signature produced using credentials whose validity period has elapsed, invalidating non-repudiation assurances.',
    expectedIndicators: [
      'Certificate validity date precedes analysis timestamp',
      'PKI trust validation reports EXPIRED',
      'Requires revocation list / CRL check'
    ],
    samplePreviewSnippet:
      'NotAfter: 2024-01-01T00:00:00Z (Expired)\nTrust Chain: Valid Root, Expired Leaf\nPKI Status: INVALID_TIME_BOUNDS'
  },
  {
    id: 'baseline-secure',
    sampleId: 'test_1_secure.txt',
    title: 'Baseline Secure Transaction (Control Case)',
    category: 'Classical Cryptography',
    severity: 'Medium',
    vector: 'Clean Authentic Artifact',
    standardsReference: 'NIST SP 800-131A Compliant',
    mechanism:
      'Valid cryptographic signature, fresh nonce, authorized X.509 certificate, and clean simulated quantum channel (< 2% QBER).',
    expectedIndicators: [
      'SHA-256 digest matches signed hash',
      'Signature status: VALID',
      'Quantum channel QBER within safe baseline bounds (1.20%)'
    ],
    samplePreviewSnippet:
      'Algorithm: RSA-2048\nSignature: VALID\nQBER: 1.20%\nOverall Status: SECURE'
  }
];

export const AttackSimulationView: React.FC<AttackSimulationViewProps> = ({ onLoadAndAnalyze }) => {
  const [selectedCategory, setSelectedCategory] = useState<'ALL' | 'Classical Cryptography' | 'Protocol & State' | 'Quantum Channel'>('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  const filteredScenarios = ATTACK_SCENARIOS.filter(scenario => {
    const matchesCategory = selectedCategory === 'ALL' || scenario.category === selectedCategory;
    const matchesSearch =
      scenario.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      scenario.vector.toLowerCase().includes(searchQuery.toLowerCase()) ||
      scenario.standardsReference.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="space-y-4">
      {/* View Header */}
      <div className="bg-[#111827] border border-[#1E293B] rounded p-4 flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xs font-bold uppercase tracking-wider text-[#F1F5F9]">
              Cyberattack Simulation Laboratory
            </h2>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded border border-[#1E293B] bg-[#162032] text-[#94A3B8]">
              8 Research Scenarios
            </span>
          </div>
          <p className="text-[11px] text-[#94A3B8] mt-1 max-w-3xl">
            Simulate and evaluate cryptographic, protocol-level, and quantum-channel attacks against Digital Signatures.
            Click &quot;Simulate &amp; Analyze&quot; to ingest each artifact directly into the Security Analyzer.
          </p>
        </div>

        <div className="text-right text-[11px] font-mono text-[#94A3B8] shrink-0">
          <div>Standards: NIST SP 800 / BB84</div>
          <div className="mt-0.5 text-[#34D399] font-semibold">Engine: Aer Simulator Ready</div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-[#111827] border border-[#1E293B] rounded p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-1.5 text-xs flex-wrap">
          <span className="text-[11px] font-semibold text-[#94A3B8] mr-1">Attack Category:</span>
          {(['ALL', 'Classical Cryptography', 'Protocol & State', 'Quantum Channel'] as const).map(cat => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-2.5 py-1 rounded text-xs font-medium border cursor-pointer transition ${
                selectedCategory === cat
                  ? 'bg-[#0284C7] text-white border-[#0284C7] font-semibold'
                  : 'bg-[#162032] text-[#94A3B8] border-[#1E293B] hover:text-[#F1F5F9] hover:bg-[#1E293B]'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="w-full sm:w-64">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search scenario or standard..."
            className="w-full px-2.5 py-1 bg-[#162032] border border-[#1E293B] rounded text-xs text-[#F1F5F9] placeholder-[#64748B] focus:outline-hidden focus:border-[#0284C7]"
          />
        </div>
      </div>

      {/* Scenarios Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
        {filteredScenarios.map((scenario) => {
          const isControl = scenario.id === 'baseline-secure';

          return (
            <div
              key={scenario.id}
              className={`bg-[#111827] border rounded p-4 flex flex-col justify-between space-y-3 transition hover:border-[#0284C7] ${
                isControl ? 'border-[#065F46]' : 'border-[#1E293B]'
              }`}
            >
              <div className="space-y-2">
                {/* Header */}
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <span className="text-[10px] font-mono uppercase text-[#94A3B8] block">
                      {scenario.category}
                    </span>
                    <h3 className="text-sm font-bold text-[#F1F5F9] mt-0.5">
                      {scenario.title}
                    </h3>
                  </div>

                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold font-mono border uppercase shrink-0 ${
                    isControl
                      ? 'bg-[#064E3B]/40 text-[#34D399] border-[#065F46]'
                      : scenario.severity === 'Critical'
                      ? 'bg-[#7F1D1D]/40 text-[#F87171] border-[#991B1B]'
                      : 'bg-[#78350F]/40 text-[#FBBF24] border-[#92400E]'
                  }`}>
                    {isControl ? 'CONTROL' : `${scenario.severity} RISK`}
                  </span>
                </div>

                {/* Threat Vector and Standards */}
                <div className="text-[11px] space-y-0.5 font-mono">
                  <div className="text-[#F1F5F9]">
                    <span className="text-[#94A3B8] font-sans">Vector:</span> {scenario.vector}
                  </div>
                  <div className="text-[#94A3B8]">
                    <span className="text-[#94A3B8] font-sans">Standard:</span> {scenario.standardsReference}
                  </div>
                </div>

                {/* Mechanism Description */}
                <p className="text-xs text-[#94A3B8] leading-relaxed font-sans">
                  {scenario.mechanism}
                </p>

                {/* Expected Indicators */}
                <div className="bg-[#162032] rounded p-2.5 border border-[#1E293B] space-y-1">
                  <span className="text-[10px] font-bold uppercase text-[#94A3B8] block font-sans">
                    Forensic Indicators to Observe:
                  </span>
                  <ul className="text-[11px] text-[#F1F5F9] space-y-0.5 font-mono">
                    {scenario.expectedIndicators.map((ind, i) => (
                      <li key={i} className="flex items-start gap-1.5">
                        <span className={isControl ? 'text-[#34D399]' : 'text-[#F87171]'}>&bull;</span>
                        <span className="leading-tight">{ind}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Snippet Preview */}
                <pre className="p-2 bg-[#0B0F17] text-[#94A3B8] border border-[#1E293B] rounded text-[10px] font-mono overflow-x-auto whitespace-pre leading-tight">
                  {scenario.samplePreviewSnippet}
                </pre>
              </div>

              {/* Action Button */}
              <div className="pt-2 border-t border-[#1E293B]">
                <button
                  onClick={() => onLoadAndAnalyze(scenario.sampleId)}
                  className={`w-full py-1.5 px-3 rounded text-xs font-mono font-semibold flex items-center justify-center gap-2 cursor-pointer border transition ${
                    isControl
                      ? 'bg-[#064E3B]/30 hover:bg-[#064E3B]/60 text-[#34D399] border-[#065F46]'
                      : 'bg-[#0284C7]/15 hover:bg-[#0284C7] text-[#38BDF8] hover:text-white border-[#0284C7]/50 hover:border-[#0284C7]'
                  }`}
                >
                  <Activity className="w-3.5 h-3.5 shrink-0" />
                  <span>Execute Vector Simulation</span>
                  <ArrowRight className="w-3.5 h-3.5 shrink-0" />
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Laboratory Simulation Disclaimer */}
      <div className="p-3 bg-[#111827] border border-[#1E293B] rounded text-[11px] text-[#94A3B8] font-mono flex flex-col sm:flex-row sm:items-center justify-between gap-1">
        <span>* Research Prototype Note: Simulation cases execute local cryptographic algorithms and Aer quantum statevector models.</span>
        <span className="shrink-0 text-[#64748B]">Environment: Qiskit Aer &bull; Bell State Φ+</span>
      </div>
    </div>
  );
};
